HomeServices.Endpoint.RazorPages.UI/Pages/Bid.cshtml.cs
using HomeService.Core.Contracts.BidContracts;
using HomeService.Core.Contracts.RequestContracts;
using HomeService.Core.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeServices.Endpoint.RazorPages.UI.Pages;

[Authorize(Roles = "Customer")]
public class BidModel : PageModel
{
    private readonly IBidAppService _bidAppService;
    private readonly IRequestAppService _requestAppService;

    public BidModel(IBidAppService bidAppService, IRequestAppService requestAppService)
    {
		_bidAppService = bidAppService;
	}

    [BindProperty]
    public ChangeStatusDto NewStatus { get; set; }


    public List<BidDto> Bids { get; set; }

    public async Task OnGet(int orderId, CancellationToken cancellationToken)
    {
        Bids = await _bidAppService.GetBidsByOrderId(orderId, cancellationToken);
    }

    //public async Task<IActionResult> OnPost(CancellationToken cancellationToken)
    //{
    //    await _requestAppService.ChangeRequestStatus(NewStatus, cancellationToken);
    //    return RedirectToPage("Index");
    //} 

    public async Task<IActionResult> OnGetActive(int id, CancellationToken cancellationToken)
	{
		await _bidAppService.Active(id, cancellationToken);
		return RedirectToPage("Index");
	}

	public async Task<IActionResult> OnGetDeActive(int id, CancellationToken cancellationToken)
	{
		await _bidAppService.DeActive(id, cancellationToken);
		return RedirectToPage("Index");
	}

    public async Task<IActionResult> OnPostDone(int bidId, CancellationToken cancellationToken)
    {
        await _bidAppService.DoneRequest(bidId, cancellationToken);
        return RedirectToPage("Index");
    }
}

HomeServices.Endpoint.RazorPages.UI/Pages/Comment.cshtml.cs
using HomeService.Core.Contracts.CommentContracts;
using HomeService.Core.Contracts.CustomerContracts;
using HomeService.Core.Contracts.ExpertContracts;
using HomeService.Core.DTOs;
using HomeService.Core.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeServices.Endpoint.RazorPages.UI.Pages;

[Authorize(Roles = "Customer,Expert")]
public class CommentModel : PageModel
{

    private readonly ICommentAppService _commentAppService;
    private readonly IExpertAppService _expertAppService;
    private readonly ICustomerAppService _customerAppService;

    public CommentModel(ICommentAppService commentAppService,
        IExpertAppService expertAppService,
        ICustomerAppService customerAppService)
    {
        _commentAppService = commentAppService;
        _expertAppService = expertAppService;
        _customerAppService = customerAppService;
    }

    [BindProperty]
    public CreateCommentDto Comment { get; set; }

    [BindProperty]
    public Expert Expert { get; set; }

    public async Task OnGet(int id, CancellationToken cancellationToken)
    {
        Expert = await _expertAppService.GetExpertById(id, cancellationToken);
    }

    public async Task<IActionResult> OnPostAsync(CancellationToken cancellationToken)
    {
        var applicationUserId = int.Parse(User.Claims.First().Value);

        if (User.IsInRole("Customer"))
        {
            int? userId;

            var user = User.Claims.FirstOrDefault(c => c.Type == "userCustomerId");
            if (user != null)
            {
                userId = int.Parse(user.Value);
            }
            else
            {
                userId = await _customerAppService.GetCustomerIdByApplicationUserId(applicationUserId, cancellationToken);
            }
            Comment.CustomerId = userId.Value;
        }
        await _commentAppService.CreateCommentDto(Comment, cancellationToken);
        return LocalRedirect("~/Index");
    }
}

HomeServices.Endpoint.RazorPages.UI/Pages/DisplayRequests.cshtml.cs
using HomeService.Core.Contracts.ExpertContracts;
using HomeService.Core.Contracts.RequestContracts;
using HomeService.Core.DTOs;
using HomeService.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading;

namespace HomeServices.Endpoint.RazorPages.UI.Pages;

public class DisplayRequestsModel : PageModel
{
	private readonly IRequestAppService _requestAppService;
    private readonly IExpertAppService _expertAppService;

    public DisplayRequestsModel(IRequestAppService requestAppService,
        IExpertAppService expertAppService)
    {
		_requestAppService = requestAppService;
        _expertAppService = expertAppService;
    }

	[BindProperty]
	public ExpertProfileDto Expert { get; set; }

	[BindProperty]
	public List<RequestDto> Orders { get; set; }

	public async Task OnGet(CancellationToken cancellationToken)
	{
        //var expertId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "userExpertId").Value);
        var applicationUserId = int.Parse(User.Claims.First().Value);
        int? userId;

        var user = User.Claims.FirstOrDefault(c => c.Type == "userExpertId");
        if (user != null)
        {
            userId = int.Parse(user.Value);
        }
        else
        {
            userId = await _expertAppService.GetExpertIdByApplicationUserId(applicationUserId, cancellationToken);
        }

        Orders = await _requestAppService.GetExpertRequest(userId, cancellationToken);
	}
}

HomeServices.Endpoint.RazorPages.UI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace HomeServices.Endpoint.RazorPages.UI.Pages;


public class ErrorModel : PageModel
{
    public void OnGet()
    {
    }
}

HomeServices.Endpoint.RazorPages.UI/Pages/ExpertComments.cshtml.cs
using System.Reflection;
using HomeService.Core.Contracts.CommentContracts;
using HomeService.Core.DTOs;
using HomeService.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeServices.Endpoint.RazorPages.UI.Pages
{
    public class ExpertCommentsModel : PageModel
    {
        private readonly ICommentAppService _commentAppService;


        [BindProperty]
        public List<CommentDto> comments { get; set; }

        public ExpertCommentsModel(ICommentAppService commentAppService)
        {
            _commentAppService = commentAppService;
        }

        public async Task OnGet(int id, CancellationToken cancellationToken)
        {
            comments = await _commentAppService.GetAllCommentsByExpertId(id, cancellationToken);
        }
    }
}

HomeServices.Endpoint.RazorPages.UI/Pages/Index.cshtml.cs
using HomeService.Core.Contracts.CategoryContracts;
using HomeService.Core.DTOs;
using HomeServices.Endpoint.RazorPages.UI.Infrastructure;
using HomeServices.Endpoint.RazorPages.UI.Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Caching.Memory;

namespace HomeServices.Endpoint.RazorPages.UI.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly IMemoryCache _memoryCache;
    private readonly IDistributedCache _distributedCache;
    private readonly ICategoryAppService _categoryAppService;


    public IndexModel(ILogger<IndexModel> logger, IMemoryCache memoryCache, IDistributedCache distributedCache, ICategoryAppService categoryAppService)
    {
        _logger = logger;
        _memoryCache = memoryCache;
        _distributedCache = distributedCache;
        _categoryAppService = categoryAppService;
    }
    public List<CategoryDto> categories { get; set; }

    public async Task OnGet(CancellationToken cancellationToken)
    {
        //categories = await _categoryAppService.GetAllCategories(cancellationToken);
    }
}

HomeServices.Endpoint.RazorPages.UI/Pages/ListingServices.cshtml.cs
using HomeService.Core.Contracts.ServiceContracts;
using HomeService.Core.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeServices.Endpoint.RazorPages.UI.Pages;

public class ListingServicesModel : PageModel
{
    private readonly IServiceAppService _serviceAppService;

    public List<ServiceDto> Services { get; set; }

    public ListingServicesModel(IServiceAppService serviceAppService)
    {
        _serviceAppService = serviceAppService;
    }
    public async Task OnGet(int categoryId, CancellationToken cancellationToken)
    {
        Services = await _serviceAppService.GetServicesByCategoryId(categoryId, cancellationToken);
    }
}

HomeServices.Endpoint.RazorPages.UI/Pages/MyRequests.cshtml.cs
using HomeService.Core.Contracts.CustomerContracts;
using HomeService.Core.Contracts.RequestContracts;
using HomeService.Core.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeServices.Endpoint.RazorPages.UI.Pages;

[Authorize(Roles = "Customer,Expert")]
public class MyRequestsModel : PageModel
{
	private readonly IRequestAppService _requestAppService;
	private readonly ICustomerAppService _customerAppService;

	public MyRequestsModel(IRequestAppService requestAppService,
		ICustomerAppService customerAppService)
	{
		_requestAppService = requestAppService;
		_customerAppService = customerAppService;
	}

	[BindProperty]
	public List<Request> Orders { get; set; }

	public async Task OnGet(CancellationToken cancellationToken)
    {
		var applicationUserId = int.Parse(User.Claims.First().Value);

		int? userId;

		var user = User.Claims.FirstOrDefault(c => c.Type == "userCustomerId");
		if (user != null)
		{
			userId = int.Parse(user.Value);
		}
		else
		{
			userId = await _customerAppService.GetCustomerIdByApplicationUserId(applicationUserId, cancellationToken);
		}
		//var userId = int.Parse(User.Claims.First(x=>x.Type == "userCustomerId").Value);
		Orders = await _requestAppService.GetRequestByCustomerId(userId, cancellationToken);
    }
}

HomeServices.Endpoint.RazorPages.UI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeServices.Endpoint.RazorPages.UI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

HomeServices.Endpoint.RazorPages.UI/Pages/Profile.cshtml.cs
using HomeService.Core.Contracts.ApplicationUser;
using HomeService.Core.Contracts.BaseService;
using HomeService.Core.Contracts.CustomerContracts;
using HomeService.Core.Contracts.ExpertContracts;
using HomeService.Core.Contracts.ServiceContracts;
using HomeService.Core.DTOs;
using HomeService.Core.Entities;
using HomeService.Core.Services.AppServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeServices.Endpoint.RazorPages.UI.Pages;

[Authorize(Roles = "Customer,Expert")]
public class ProfileModel : PageModel
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IAccountAppService _accountAppServices;
    private readonly IBaseAppService _baseAppServices;
    private readonly ICustomerAppService _customerAppServices;
    private readonly IExpertAppService _expertAppService;
    private readonly IServiceAppService _serviceAppService;

    [BindProperty]
    public IFormFile Image { get; set; }


    [BindProperty]
    public CustomerProfileDto Customer { get; set; }

    [BindProperty]
    public ExpertProfileDto Expert { get; set; }


    public List<ServiceDto> Services { get; set; }

    public ProfileModel(UserManager<ApplicationUser> userManager,
        IAccountAppService accountAppServices,
        IBaseAppService baseAppServices,
        ICustomerAppService customerAppServices,
        IExpertAppService expertAppService,
        IServiceAppService serviceAppService)
    {
        _userManager = userManager;
        _accountAppServices = accountAppServices;
        _baseAppServices = baseAppServices;
        _customerAppServices = customerAppServices;
        _expertAppService = expertAppService;
        _serviceAppService = serviceAppService;
    }

    public async Task OnGet(CancellationToken cancellationToken)
    {
        var applicationUserId = int.Parse(User.Claims.First().Value);

        if (User.IsInRole("Customer"))
        {
            int? userId;

            var user = User.Claims.FirstOrDefault(c => c.Type == "userCustomerId");
            if (user != null)
            {
                userId = int.Parse(user.Value);
            }
            else
            {
                userId = await _customerAppServices.GetCustomerIdByApplicationUserId(applicationUserId, cancellationToken);
            }
            //int userId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "userCustomerId").Value);
            TempData["CustomerId"] = userId;
            Customer = await _accountAppServices.GetCustomer(userId, applicationUserId, cancellationToken);
        }
        if (User.IsInRole("Expert"))
        {
            Services = await _serviceAppService.GetAllServices(cancellationToken);
            int? userId;

            var user = User.Claims.FirstOrDefault(c => c.Type == "userExpertId");
            if (user != null)
            {
                userId = int.Parse(user.Value);
            }
            else
            {
                userId = await _expertAppService.GetExpertIdByApplicationUserId(applicationUserId, cancellationToken);
            }
            //int userId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "userExpertId").Value);
            TempData["ExpertId"] = userId;
            Expert = await _accountAppServices.GetExpert(userId, applicationUserId, cancellationToken);
        }
    }

    public async Task<IActionResult> OnPostUpdateCustomer(IFormFile image, CancellationToken cancellationToken)
    {
        if (image != null)
        {
            var imageUrl = await _baseAppServices.UploadImage(image);
            Customer.ProfileImgUrl = imageUrl;
        }
        await _customerAppServices.UpdateCustomer(Customer, cancellationToken);
        return LocalRedirect("/Profile");
    }

    public async Task<IActionResult> OnPostUpdateExpert(IFormFile image, CancellationToken cancellationToken)
    {
        if (image != null)
        {
            var imageUrl = await _baseAppServices.UploadImage(image);
            Expert.ProfileImgUrl = imageUrl;
        }
        await _expertAppService.UpdateExpert(Expert, cancellationToken);
        return LocalRedirect("/Profile");
    }
}



















//public async Task<IActionResult> OnPostExpert(ExpertDto expertDto, IFormFile image, CancellationToken cancellationToken)
//{
//    var imageUrl = await _baseAppServices.UploadImage(image);
//    expertDto.ProfileImgUrl = imageUrl;
//    await _expertAppService.CreateExpert(expertDto, cancellationToken);
//    return LocalRedirect("/Profile");
//}

//public async Task<IActionResult> OnPostCustomer(CustomerDto customerDto, IFormFile image, CancellationToken cancellationToken)
//{
//    var imageUrl = await _baseAppServices.UploadImage(image);
//    customerDto.ProfileImgUrl = imageUrl;
//    await _customerAppServices.CreateCustomer(customerDto, cancellationToken);
//    return LocalRedirect("/Profile");
//}

HomeServices.Endpoint.RazorPages.UI/Pages/RequestDetails.cshtml.cs
using HomeService.Core.Contracts.BidContracts;
using HomeService.Core.Contracts.ExpertContracts;
using HomeService.Core.Contracts.RequestContracts;
using HomeService.Core.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeServices.Endpoint.RazorPages.UI.Pages;

public class RequestDetailsModel : PageModel
{
    private readonly IRequestAppService _requestAppService;
    private readonly IBidAppService _bidAppService;
    private readonly IExpertAppService _expertAppService;

    public RequestDetailsModel(IRequestAppService requestAppService,
        IBidAppService bidAppService,
        IExpertAppService expertAppService)
    {
        _requestAppService = requestAppService;
        _bidAppService = bidAppService;
        _expertAppService = expertAppService;
    }

    public RequestDto Order { get; set; }

    [BindProperty]
    public int ExpertId { get; set; }

    public async Task OnGet(int orderId, CancellationToken cancellationToken)
    {
        Order = await _requestAppService.GetRequestById(orderId, cancellationToken);

        var applicationUserId = int.Parse(User.Claims.First().Value);
        int? userId;

        var user = User.Claims.FirstOrDefault(c => c.Type == "userExpertId");
        if (user != null)
        {
            userId = int.Parse(user.Value);
        }
        else
        {
            userId = await _expertAppService.GetExpertIdByApplicationUserId(applicationUserId, cancellationToken);
        }
        ExpertId = userId.Value;
    }

    public async Task<IActionResult> OnGetCreateBid(int id, CancellationToken cancellationToken)
    {
        var applicationUserId = int.Parse(User.Claims.First().Value);
        int? userId;

        var user = User.Claims.FirstOrDefault(c => c.Type == "userExpertId");
        if (user != null)
        {
            userId = int.Parse(user.Value);
        }
        else
        {
            userId = await _expertAppService.GetExpertIdByApplicationUserId(applicationUserId, cancellationToken);
        }

        var bidModel = new CreateBidDto()
        {
            RequestId = id,
            ExpertId = userId.Value,
        };
        await _bidAppService.CreateBidByRequestId(bidModel, cancellationToken);
        return LocalRedirect("~/DisplayRequests");
    }
}

HomeServices.Endpoint.RazorPages.UI/Pages/Bid.cshtml
@page
@using Framework
@using HomeService.Core.Contracts.CommentContracts
@using HomeService.Core.Enums
@using HomeService.Core.Services.AppServices
@using Microsoft.AspNetCore.Mvc.TagHelpers
@inject ICommentAppService CommentAppService;
@model HomeServices.Endpoint.RazorPages.UI.Pages.BidModel
@{
    Layout = "Shared/_Layout-Account";
}
<!-- ======================= dashboard Detail ======================== -->
<div class="goodup-dashboard-content">
    <div class="dashboard-widg-bar d-block">
        <div class="row">
            <div class="col-xl-12 col-lg-12">
                <div class="dashboard-list-wraps bg-white rounded mb-4">
                    <div class="dashboard-list-wraps-head br-bottom py-3 px-3">
                        <div class="dashboard-list-wraps-flx">
                            <h4 class="mb-0 ft-medium fs-md"><i class="fas fa-shopping-basket ms-2 theme-cl fs-sm"></i>لیست رزروها</h4>
                        </div>
                    </div>
                    <div class="dashboard-list-wraps-body py-3 px-3">
                        <div class="dashboard-bookings-wraps">
                            <!-- Single booking List -->
                            @if (Model.Bids.Count() == 0)
                            {
                                <h4 class="ft-bold mb-1 ff-second fs-5"><span style="color: red">هنوز هیچ پیشنهادی از سمت کارشناسی برای شما ارسال نشده است</span></h4>
                            }
                            else
                            {
                                @foreach (var bid in Model.Bids)
                                {
                                    <div class="dsd-single-bookings-wraps">
                                        <div class="dsd-single-book-thumb"><a asp-route-expertId="@bid.ExpertId" asp-page="Comment"><img src="@bid.Expert.ProfileImgUrl" class="img-fluid circle" alt="" /></a></div>
                                        <div class="dsd-single-book-caption">
                                            <div class="dsd-single-book-title"><h5>@bid.Expert.FirstName @bid.Expert.LastName</h5></div>
                                            <div class="ico-content">
                                                @if (@bid.IsWinner == true)
                                                {
                                                    <ul>
                                                        <li>
                                                            <div class="px-2 py-1 medium bg-light-success rounded text-success">برنده شده</div>
                                                        </li>
                                                    </ul>
                                                }
                                            </div>
                                            <div class="dsd-single-descr">
                                                <div class="dsd-single-item"><span class="dsd-item-title">نام:</span><span class="dsd-item-info">@bid.Expert.FirstName @bid.Expert.LastName</span></div>
                                                <div class="dsd-single-item"><span class="dsd-item-title">تاریخ رزرو:</span><span class="dsd-item-info">@bid.DateOfRegisteration.ToPersianString("yyyy/MM/dd")</span></div>
                                                <div class="dsd-single-item"><span class="dsd-item-title">پست الکترونیک:</span><span class="dsd-item-info">@bid.Expert.ApplicationUser.Email</span></div>
                                                <div class="dsd-single-item"><span class="dsd-item-title">شماره تماس:</span><span class="dsd-item-info">@bid.Expert.PhoneNumber</span></div>
                                                <div class="dsd-single-item"><span class="dsd-item-title">مبلغ:</span><span class="dsd-item-info">@bid.ProposedPrice</span></div>
                                            </div>
                                            @if (Model.Bids.Any(x => x.IsWinner == true))
                                            {
                                                @if (@bid.IsWinner == false)
                                                {
                                                    <div>
                                                        <a class="btn btn-danger">رد شده</a>
                                                    </div>
                                                }
                                                else
                                                {
                                                    <div class="dsd-single-bookings-wraps">

                                                        <form asp-page-handler="Done" method="post">
                                                            <input type="hidden" name="bidId" value="@bid.Id" />
                                                            <button class="btn btn-success" type="submit"><i class="fas fa-check-circle ms-1"></i>کار به پایان رسید</button>
                                                            <a class="btn btn-primary" asp-route-id="@bid.Expert.Id" asp-page="comment"><i class="fas fa-check-circle ms-1"></i>ثبت نظر برای کارشناس</a>
                                                        </form>

                                                    </div>
                                                }
                                            }
                                            else
                                            {
                                                <a asp-route-id="@bid.Id" asp-page-handler="Active" class="btn btn-success "><i class="fas fa-check-circle ms-1"></i>تایید </a>
                                            }

                                            @if (await CommentAppService.HaveComment(@bid.Expert.Id,default))
                                            {
                                                <a asp-route-id="@bid.Expert.Id" asp-page="ExpertComments"  class="btn btn-warning ">سوابق نظرات کارشناس</a>
                                            }
                                        </div>

                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HomeServices.Endpoint.RazorPages.UI/Pages/ExpertComments.cshtml
@page
@using Framework
@model HomeServices.Endpoint.RazorPages.UI.Pages.ExpertCommentsModel
@{
    Layout = "Shared/_Layout-Account";
}
<div class="goodup-dashboard-content">
    <div class="dashboard-widg-bar d-block mb-5  bg-whit">
    <div class="row">

        <div class="table table-responsive">
            <table class="table table-striped table-hover table-borderless table-sm ">
                <thead>
                <tr>
                    <th scope="col">نام کارشناس</th>
                    <th scope="col">متن</th>
                    <th scope="col">امتیاز</th>
                    <th scope="col">تاریخ ایجاد</th>
                </tr>
                </thead>
                <tbody>

                @foreach (var comment in @Model.comments)
                {
                    <tr>
                        <td>@comment.Expert.FirstName @comment.Expert.LastName</td>
                        <td>@comment.CommentText</td>
                        <td>@comment.Score</td>
                        <td>@comment.CreatAt.ToPersianString("yyyy/MM/dd")</td>
                    </tr>
                }
                </tbody>

            </table>
        </div>
    </div>
</div>
</div>

HomeServices.Endpoint.RazorPages.UI/Pages/RequestDetails.cshtml
@page
@using Framework
@model HomeServices.Endpoint.RazorPages.UI.Pages.RequestDetailsModel
@{
    Layout = "Shared/_Layout-Account";
}
<!-- ======================= dashboard Detail ======================== -->
<div class="goodup-dashboard-content">
    <div class="dashboard-widg-bar d-block">
        <div class="row">
            <div class="col-xl-12 col-lg-12">
                <div class="dashboard-list-wraps bg-white rounded mb-4">
                    <div class="dashboard-list-wraps-head br-bottom py-3 px-3">
                        <div class="dashboard-list-wraps-flx">
                            <h4 class="mb-0 ft-medium fs-md"><i class="fas fa-shopping-basket ms-2 theme-cl fs-sm"></i>لیست رزروها</h4>
                        </div>
                    </div>
                    <div class="dashboard-list-wraps-body py-3 px-3">
                        <div class="dashboard-bookings-wraps">
                            <!-- Single booking List -->
                            <div class="dsd-single-bookings-wraps">
                                <div class="dsd-single-book-thumb"><a asp-route-expertId="@Model.Order.ServiceName" asp-page="Comment"><img src="" class="img-fluid circle" alt="" /></a></div>
                                <div class="dsd-single-book-caption">
                                    <div class="dsd-single-book-title"><h5>@Model.Order.Customer.FirstName @Model.Order.Customer.LastName</h5></div>
                                    @if (@Model.Order.Status == HomeService.Core.Enums.RequestStatus.CheckingAndWaitingExpert)
                                    {
                                    <div class="ico-content">
                                        <ul>
                                            <li><div class="px-2 py-1 medium bg-light-success rounded">پیشنهاد شما توسط مشتری تایید شد و در انتظار تماس شماست</div></li>
                                        </ul>
                                    </div>
                                    }
                                    @if (@Model.Order.Status == HomeService.Core.Enums.RequestStatus.Registered && !Model.Order.Bids.Any(x => x.ExpertId == Model.ExpertId))
                                    {
                                        <div class="ico-content">
                                            <ul>
                                                <li><div class="px-2 py-1 medium bg-light-wrning rounded text-warning">درخواست توسط مشتری ثبت شده است</div></li>
                                            </ul>
                                        </div>
                                    }
                                    @if (@Model.Order.Status == HomeService.Core.Enums.RequestStatus.Registered && Model.Order.Bids.Any(x => x.ExpertId == Model.ExpertId))
                                    {
                                        <div class="ico-content">
                                            <ul>
                                                <li><div class="px-2 py-1 medium bg-light-wrning rounded text-warning">پیشنهاد شما هنوز توسط مشتری تایید نشده</div></li>
                                            </ul>
                                        </div>
                                    }
                                    @if (@Model.Order.Status == HomeService.Core.Enums.RequestStatus.Rejected)
                                    {
                                        <div class="ico-content">
                                            <ul>
                                                <li><div class="px-2 py-1 medium bg-light-danger rounded text-danger">پیشنهاد شما توسط مشتری رد شد</div></li>
                                            </ul>
                                        </div>
                                    }
                                    @if (@Model.Order.Status == HomeService.Core.Enums.RequestStatus.Done)
                                    {
                                        <div class="ico-content">
                                            <ul>
                                                <li><div class="px-2 py-1 medium bg-light-success rounded text-success">کار به پایان رسید</div></li>
                                            </ul>
                                        </div>
                                    }

                                    <div class="dsd-single-descr">
                                        <div class="dsd-single-item"><span class="dsd-item-title">تاریخ رزرو:</span><span class="dsd-item-info">@Model.Order.Customer.CreatAt.ToPersianString("yyyy/MM/dd")</span></div>
                                        <div class="dsd-single-item"><span class="dsd-item-title">پست الکترونیک:</span><span class="dsd-item-info">@Model.Order.Customer.ApplicationUser.Email</span></div>
                                        <div class="dsd-single-item"><span class="dsd-item-title">شماره تماس:</span><span class="dsd-item-info">@Model.Order.Customer.PhoneNumber</span></div>
                                        <div class="dsd-single-item"><span class="dsd-item-title">مبلغ:</span><span class="dsd-item-info">@Model.Order.Service.Price</span></div>
                                    </div>
                                    @if (!Model.Order.Bids.Any(x => x.ExpertId == Model.ExpertId))
                                    {
                                        <a asp-page-handler="CreateBid" asp-route-id="@Model.Order.Id" class="btn btn-success"><i class="fas fa-check-circle ms-1"></i>ایجاد پیشنهاد </a>
                                    }
                                    else
                                    {
                                        <p>شما قبلا برای این درخواست ثبت کرده اید</p>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>