HomeServices.Endpoint.RazorPages.UI/Areas/Admin/Pages/CategoryManagement/Create.cshtml.cs
using HomeService.Core.Contracts.CategoryContracts;
using HomeService.Core.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeServices.Endpoint.RazorPages.UI.Areas.Admin.Pages.CategoryManagement;

[Authorize(Roles ="Admin")]
public class CreateModel : PageModel
{

    private readonly ICategoryAppService _categoryAppService;

    [BindProperty]
    public CategoryDto Category { get; set; }

    public CreateModel(ICategoryAppService categoryAppServices)
    {
        _categoryAppService = categoryAppServices;
    }

    public async Task OnGet()
    {
    }

    public async Task<IActionResult> OnPost(CancellationToken cancellationToken)
    {
        await _categoryAppService.CreateCategory(Category, cancellationToken);
        return RedirectToPage("Index");
    }
}

HomeServices.Endpoint.RazorPages.UI/Areas/Admin/Pages/CategoryManagement/Update.cshtml.cs
using HomeService.Core.Contracts.CategoryContracts;
using HomeService.Core.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeServices.Endpoint.RazorPages.UI.Areas.Admin.Pages.CategoryManagement;

[Authorize(Roles = "Admin")]
public class UpdateModel : PageModel
{
    private readonly ICategoryAppService _categoryAppService;

    public UpdateModel(ICategoryAppService categoryAppService)
    {
        _categoryAppService = categoryAppService;
    }

    [BindProperty]
    public CategoryDto Category { get; set; }

    [BindProperty]
    public int Id { get; set; }


    public async Task OnGet(int id, CancellationToken cancellationToken)
    {
        Category = await _categoryAppService.GetCategoryById(id, cancellationToken);
        Id = id;
    }

    public async Task<IActionResult> OnPost(CancellationToken cancellationToken)
    {
        await _categoryAppService.UpdateCategory(Category, cancellationToken);
        return RedirectToPage("Index");
    }
}

HomeServices.Endpoint.RazorPages.UI/Areas/Admin/Pages/ServiceManagement/Create.cshtml.cs
using HomeService.Core.Contracts.CategoryContracts;
using HomeService.Core.Contracts.ServiceContracts;
using HomeService.Core.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Threading;

namespace HomeServices.Endpoint.RazorPages.UI.Areas.Admin.Pages.ServiceManagement;

[Authorize(Roles = "Admin")]
public class CreateModel : PageModel
{
    private readonly IServiceAppService _serviceAppService;
    private readonly ICategoryAppService _categoryAppService;

    [BindProperty]
    public ServiceDto Service { get; set; }

    [BindProperty]
    public List<ServiceDto> Services { get; set; }

    [BindProperty]
    public List<CategoryDto> Categories { get; set; }

    public CreateModel(IServiceAppService serviceAppServices, ICategoryAppService categoryAppService)
    {
        _serviceAppService = serviceAppServices;
        _categoryAppService = categoryAppService;
    }

    public async Task OnGet(CancellationToken cancellationToken)
    {
        Services = await _serviceAppService.GetAllServices(cancellationToken);
        Categories = await _categoryAppService.GetAllCategories(cancellationToken);
    }

    public async Task<IActionResult> OnPost(CancellationToken cancellationToken)
    {
        await _serviceAppService.CreateService(Service, cancellationToken);
        return RedirectToPage("Index");
    }
}

HomeServices.Endpoint.RazorPages.UI/Areas/Admin/Pages/ServiceManagement/Index.cshtml.cs
using HomeService.Core.Contracts.ServiceContracts;
using HomeService.Core.DTOs;
using HomeService.Infrastructure.DataAccess.Repo.Ef.Cache.InMemoryCache;
using HomeServices.Endpoint.RazorPages.UI.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeServices.Endpoint.RazorPages.UI.Areas.Admin.Pages.ServiceManagement;

[Authorize(Roles = "Admin")]
public class IndexModel : PageModel
{
    private readonly IServiceAppService _serviceAppService;
    private readonly IInMemoryCacheService _inMemoryCacheService;

    public List<ServiceDto> Services { get; set; }

    public IndexModel(IServiceAppService serviceAppService, IInMemoryCacheService inMemoryCacheService)
    {
        _serviceAppService = serviceAppService;
        _inMemoryCacheService = inMemoryCacheService;
    }

    public async Task OnGet(CancellationToken cancellationToken)
    {
        //var cacheData = _inMemoryCacheService.Get<List<ServiceDto>>(CacheKey.Services);
        //if (cacheData == null)
        //{
        Services = await _serviceAppService.GetAllServices(cancellationToken);
        //    _inMemoryCacheService.SetSliding(CacheKey.Services, Services, 10);
        //}
    }

    public async Task<IActionResult> OnGetDelete(int id, CancellationToken cancellationToken)
    {
        await _serviceAppService.DeleteServiceById(id, cancellationToken);
        return RedirectToPage("Index");
    }

    public async Task<IActionResult> OnPostActive(int id, CancellationToken cancellationToken)
    {
        await _serviceAppService.Active(id, cancellationToken);
        return RedirectToPage("Index");
    }

    public async Task<IActionResult> OnPostDeActive(int id, CancellationToken cancellationToken)
    {
        await _serviceAppService.DeActive(id, cancellationToken);
        return RedirectToPage("Index");
    }
}

HomeServices.Endpoint.RazorPages.UI/Areas/Admin/Pages/ServiceManagement/Update.cshtml.cs
using HomeService.Core.Contracts.CategoryContracts;
using HomeService.Core.Contracts.ServiceContracts;
using HomeService.Core.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeServices.Endpoint.RazorPages.UI.Areas.Admin.Pages.ServiceManagement;

[Authorize(Roles = "Admin")]
public class UpdateModel : PageModel
{

    private readonly IServiceAppService _serviceAppService;
    private readonly ICategoryAppService _categoryAppService;

    public UpdateModel(IServiceAppService serviceAppService, ICategoryAppService categoryAppService)
    {
        _serviceAppService = serviceAppService;
        _categoryAppService = categoryAppService;
    }

    [BindProperty]
    public List<ServiceDto> Services { get; set; }

    [BindProperty]
    public List<CategoryDto> Categories { get; set; }

    [BindProperty]
    public ServiceDto Service { get; set; }

    [BindProperty]
    public int Id { get; set; }

    public async Task OnGet(int id, CancellationToken cancellationToken)
    {
        Categories = await _categoryAppService.GetAllCategories(cancellationToken);
        Service = await _serviceAppService.GetServiceById(id, cancellationToken);
        Id = id;
    }

    //public async Task<IActionResult> OnPost(CancellationToken cancellationToken)
    //{
    //    await _serviceAppService.UpdateService(Service, cancellationToken);
    //    return RedirectToPage("Index");
    //}
    public async Task<IActionResult> OnPost(CancellationToken cancellationToken)
    {
        if (ModelState.IsValid)
        {
            await _serviceAppService.UpdateService(Service, cancellationToken);
        }
        return RedirectToPage("Index");
    }
}

HomeServices.Endpoint.RazorPages.UI/Areas/Admin/Pages/ServiceManagement/Create.cshtml
@page
@using HomeService.Core.Contracts.CategoryContracts
@using HomeService.Core.Contracts.ServiceContracts
@using HomeService.Core.Services.AppServices
@inject ICategoryAppService CategoryAppService
@inject IServiceAppService ServiceAppService
@model HomeServices.Endpoint.RazorPages.UI.Areas.Admin.Pages.ServiceManagement.CreateModel
@{
    Layout = "Shared/_AdminLayout";
    ViewData["Title"] = "ایجاد سرویس";
}

<div class="portlet-body" style="">
    <form method="post">
        <div class="form-body">
            <div class="input-group">
                <select asp-for="@Model.Service.CategoryId">
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <input asp-for="@Model.Service.Title" type="text" class="form-control" placeholder="عنوان سرویس را وارد کنید">
                <input asp-for="@Model.Service.Description" type="text" class="form-control" placeholder="توضیحات سرویس را وارد کنید">
                <input asp-for="@Model.Service.Price" type="text" class="form-control" placeholder="قیمت سرویس را وارد کنید">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">ایجاد سرویس<div class="paper-ripple"><div class="paper-ripple__background"></div><div class="paper-ripple__waves"></div></div></button>
                </span>
            </div>
        </div>
    </form>
    <hr>
</div>
<h3>خدمات موجود</h3>
<ul>
    @foreach (var service in await ServiceAppService.GetAllServices(default))
    {
        <li>@service.Title</li>
    }
</ul>

HomeServices.Endpoint.RazorPages.UI/Areas/Admin/Pages/ServiceManagement/Index.cshtml
@page
@using HomeService.Core.Contracts.ServiceContracts
@using HomeService.Core.Contracts.CategoryContracts
@inject IServiceAppService ServiceAppService
@model HomeServices.Endpoint.RazorPages.UI.Areas.Admin.Pages.ServiceManagement.IndexModel
@{
    Layout = "Shared/_AdminLayout";
    ViewData["Title"] = "مدیریت خدمات";
}

<a href="@Url.Page("Create")" type="button" class="btn rounded-pill btn-info mb-2">افزودن سرویس جدید</a>
<div class="table-responsive text-nowrap">
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th>شناسه</th>
                <th>نام</th>
                <th>نام دسته بندی</th>
                <th>توضیحات</th>
                <th>قیمت</th>
                <th>تصویر</th>
                <th>وضعیت</th>
                <th>عملیات</th>
            </tr>
        </thead>
        <tbody class="table-border-bottom-0">
            @if (Model.Services != null)
            {
                @foreach (var service in await @ServiceAppService.GetAllServices(default))
                {
                    @* @if (category.IsDeleted != true)
            { *@
                    <tr>
                        <td>@service.Id</td>
                        <td>@service.Title</td>
                        <td>@service.Category.Name</td>
                        <td>@service.Description</td>
                        <td>@service.Price</td>
                        <td>@service.ImgUrl</td>
                        <td>
                            @if (service.IsDeleted == true)
                            {
                                <form method="post" asp-page-handler="Active">
                                    <input type="hidden" name="id" value="@service.Id">
                                    <button class="btn btn-success" type="submit">فعال کردن</button>
                                </form>
                            }
                            else
                            {
                                <form method="post" asp-page-handler="DeActive">
                                    <input type="hidden" name="id" value="@service.Id">
                                    <button class="btn btn-danger round" type="submit">غیرفعال کردن</button>
                                </form>
                            }
                        </td>
                        <td>

                            <div class="dropdown">
                                <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                    <i class="bx bx-dots-vertical-rounded"></i>
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-page="Update" asp-route-id="@service.Id" class="bx bx-edit-alt me-1">ویرایش</a>
                                    <a class="dropdown-item" asp-page-handler="Delete" asp-route-id="@service.Id" onclick="return confirm('Are you sure?')" class="bx bx-trash me-1">حذف</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @* } *@
                }
            }
        </tbody>
    </table>
</div>

HomeServices.Endpoint.RazorPages.UI/Areas/Admin/Pages/ServiceManagement/Update.cshtml
@page
@model HomeServices.Endpoint.RazorPages.UI.Areas.Admin.Pages.ServiceManagement.UpdateModel
@{
}
@{
    Layout = "Shared/_AdminLayout";
    ViewData["Title"] = "بروزرسانی سرویس";
}
<div class="portlet-body" style="">
    <form method="post">
        <div class="form-body">
            <div class="input-group">
                <select asp-for="@Model.Service.CategoryId">
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <input asp-for="@Model.Service.Title" type="text" class="form-control" placeholder="عنوان سرویس جدید را وارد کنید">
                <input asp-for="@Model.Service.Description" type="text" class="form-control" placeholder="توضیحات سرویس جدید را وارد کنید">
                <input asp-for="@Model.Service.Price" type="text" class="form-control" placeholder="قیمت سرویس جدید را وارد کنید">
                <span class="input-group-btn">
                    <input asp-for="@Model.Service.Id" type="hidden"></input>
                    <button class="btn btn-primary" type="submit">
                        ویرایش سرویس<div class="paper-ripple">
                            <div class="paper-ripple__background"></div>
                            <div class="paper-ripple__waves"></div>
                        </div>
                    </button>
                </span>
            </div>
        </div>
    </form>
    <hr>
</div>